# Generated by Django 3.1 on 2022-03-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220328_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='usertype',
            field=models.CharField(default='admin', max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='usertype',
            field=models.CharField(default='customer', max_length=128),
        ),
    ]
