# Generated by Django 3.1 on 2022-05-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220328_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='usertype',
            field=models.CharField(default='Farmer', max_length=128),
        ),
    ]
