# Generated by Django 3.1 on 2022-05-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220504_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customer_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='usertype',
            field=models.CharField(default='farmer', max_length=128),
        ),
    ]
