# Generated by Django 3.1 on 2022-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220504_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='mobile'),
        ),
    ]
