# Generated by Django 3.1 on 2022-05-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20220504_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.DateTimeField(auto_now=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='user.customer')),
            ],
            options={
                'verbose_name': 'CustomerOrder',
                'verbose_name_plural': 'CustomerOrder',
                'db_table': 'CustomerOrder',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CustomerOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_items', to='order.customerorder')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItem',
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='FarmerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.DateTimeField(auto_now=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CustomerOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_order_farmer_orders', to='order.customerorder')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_orders', to='user.farmer')),
            ],
            options={
                'verbose_name': 'FarmerOrder',
                'verbose_name_plural': 'FarmerOrder',
                'db_table': 'FarmerOrder',
            },
        ),
    ]
